services:
  recipe-book-api:
    image: "recipe-book-api"
    container_name: recipe-book-api
    volumes:
      - /etc/secrets/:/etc/secrets/
    ports:
      - "9595:5555"
    build:
      target: prod
      context: .
      dockerfile: Dockerfile
    restart: always